### ISSUE TITLE
Hi any chance you can provide the trained soccer summarizer+celebration clsf model weights?

### ISSUE THREAD

**Issue by SamSamhuns** [AlexanderSlav/Automatic-Soccer-Highlights-Generation#1]
Or if you can provide the link to your annotated training data through a google drive link

**Comment by AlexanderSlav** [comment]
Hi, sure, I'll update the repo with detailed Readme and links for weights. But I should mention that this research was done for my course work and it's not suitable yet for production.
The video summarization approach using Dsnet failed with my domain due to several reasons: not enough training data, global attention not suitable for videos with long duration. 
The celebration classification approach plus evristic that cuts goals moment from game record works pretty fine. But important notice here: my training data were futsal games from this [channel](https://www.youtube.com/channel/UCRheEKZEJtF8jfxkQPxZZbw). This is not classic soccer.
